name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 저장소 코드 체크아웃
      - name: Checkout
        uses: actions/checkout@v4

      # JDK 17 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle' # Gradle 캐시 설정으로 빌드 속도 향상

      # gradlew 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Lint 실행 (정적 분석)
      - name: Run Lint
        run: ./gradlew lintDebug

      # 앱 빌드 (컴파일 검증)
      - name: Build with Gradle
        run: ./gradlew assembleDebug
